### ISSUE TITLE
npm install fails with error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?

### ISSUE THREAD

**Issue by elecoest** [CodyHouse/codyframe-gulp-starter-template#1]
If you have this error like me,

First:

`yarn add gulp-sass@5.0.0
`yarn add gulp-dart-sass@^1.0.2

yarn install will work with these deps properly.

We need to fix the following line from

`import sass from 'gulp-sass';
`
to

`var sass = require('gulp-sass')(require('sass'));
`
in the following files: gulpfile.js

**Comment by claudia-romano** [comment]
Hi there, the starter template uses gulp-sass v4 which uses the compiler property to set the sass compiler:
```
var sass = require('gulp-sass');
sass.compiler = require('sass');
```

If upgrading to v5 (as you did), you'll need to use the new syntax:
```
var sass = require('gulp-sass')(require('sass'));
```

We'll make sure to update the package and the gulpfile to this new version. Thanks!
