### ISSUE TITLE
how to use the php version of this starter template?

### ISSUE THREAD

**Issue by zhampu** [CodyHouse/codyframe-gulp-starter-template#3]
Hello,
Im trying to integrate Codyframe with Kirby by following this [https://codyhouse.co/ds/docs/framework#gulp-php](https://codyhouse.co/ds/docs/framework#gulp-php) however after changing the gulp.js [file to this one](https://gist.github.com/claudia-romano/98fbfcbd498c7c57d121559d5c90984d) and changing the index.html file to index.php there is nothing that appears in the browsersync.

could someone please let me know is the gulp.js is correct?

**Comment by claudia-romano** [comment]
Hi there, could you please provide more info about the issue? For example, do you get an error message in the console, is your project page showing up but not refershing? Also, could you share the structure of your project? Thank you.

**Comment by claudia-romano** [comment]
I'm closing this issue since no additional info was provided. Feel free to reopen it if you are still having problems. Cheers!
